name: Sync daily folder
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  sync_daily_folder:
    name: Sync daily folder
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: "read"

    steps:
      - name: Create dirs
        run: |
          mkdir -p download/api

      - name: Download Daily api test report
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RUN_ID: 2445462717
          ARTIFACT_NAME: api-test-report---daily
        working-directory: download/api
        run: |
          gh run download $RUN_ID \
            --name $ARTIFACT_NAME \
            --repo woocommerce/woocommerce

      - name: Try gcloud
        run: |
          gcloud version
          gcloud config get-value project
